apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -e2e

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: invaleed/argo-demo
  newTag: 98d1bcb626e493639842cd0cee058a6a95f46ca5
resources:
- ../base
