apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -prod

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: invaleed/argo-demo
  newTag: 951d75d90eb63ed20361b912e68447e41d8552ba
resources:
- ../base
